### ISSUE TITLE
OTD Crashes at start while having Windows Ink installed

### ISSUE THREAD

**Issue by ienooo** [X9VoiD/VoiDPlugins#31] opened 2022-03-19 18:56 UTC
OTD opens at first but then crashes while trying to connect to OpenTabletDriver.Daemon.exe. 
I'm not getting an error message except for once where it just said Fatal Error and asked me to restart OTD.
VMulti is installed.

Deamon Log only has following:

```
19.03.2022 19:50:58
System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
System.Private.CoreLib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.TriggerEventMethods(Object obj, TabletReference tabletReference)
   at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.Construct[T](IServiceManager provider, TabletReference tabletReference)
   at OpenTabletDriver.Daemon.DriverDaemon.SetBindingHandlerSettings(InputDeviceTree dev, IOutputMode outputMode, BindingSettings settings, TabletReference tabletReference)
   at OpenTabletDriver.Daemon.DriverDaemon.SetSettings(Settings settings)
   at OpenTabletDriver.Daemon.DriverDaemon.LoadUserSettings()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
InvokeMethod
```

EDIT: When installing Windows Ink via the Plugin Manager and then using it as output method and saving it gives those two errors when trying to uninstall it again. Doesn't happen with other plugins I've tested.

1.
![image](https://user-images.githubusercontent.com/82706826/159135102-9ea6731f-1979-46b2-b686-f6c2b1b6849d.png)

2.
![image](https://user-images.githubusercontent.com/82706826/159135116-bea80fa7-d56a-486f-a211-8274af0c61be.png)

**Comment by X9VoiD** [comment] 2022-03-24 05:36
Duplicate of #29

**Closed by X9VoiD** 2022-03-24 05:36 UTC
